groups:
  - name: Umee
    rules:
      - alert: Umeed_Log_ERR_detected
        expr: count_over_time ({unit="umeed.service"} |~ "ERR.*"[1m]) >= 1
        for: 0m
        labels:
            severity: warning
            category: logs
        annotations:
            title: "Umeed logged an ERR"
            description: "Umeed logged an ERR"
            logurl: "https://pops.one"
      - alert: Peggod_Log_ERR_detected
        expr: count_over_time ({unit="peggod.service"} |~ "ERR.*"[1m]) >= 1
        for: 0m
        labels:
            severity: warning
            category: logs
        annotations:
            title: "Peggod logged an ERR"
            description: "Peggod logged an ERR"
            logurl: "https://pops.one"