groups:
  - name: Umee
    rules:
    - alert: NodeStuck
      expr: delta(tendermint_consensus_height[5m]) == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "The umee node {{ $labels.instance }} is stuck"
        description: "The umee node {{ $labels.instance }} is stuck"

    - alert: lowP2Pconnection
      expr: tendermint_p2p_peers < 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "The umee node {{ $labels.instance }} is having less than 2 peers connected for 5min"
        description: "The umee node {{ $labels.instance }} is currently connected to {{ $value }}"

    - alert: FastSyncing
      expr: tendermint_consensus_fast_syncing == 1
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "The umee node {{ $labels.instance }} is currently fast syncing for 1m"
        description: "The umee node {{ $labels.instance }} is currently fast syncing for 1m"

    - alert: StateSyncing
      expr: tendermint_consensus_state_syncing == 1
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "The umee node {{ $labels.instance }} is currently state syncing for 1m"
        description: "The umee node {{ $labels.instance }} is currently state syncing"

    - alert: UnusualBlocktime
      expr: 60 / (delta(tendermint_consensus_block_interval_seconds_count[30m])/30) > 24
      for: 1m
      labels:
        severity: info
      annotations:
        summary: "The umee node {{ $labels.instance }} or network block time is more than 24s"
        description: "The umee node {{ $labels.instance }} or network block time is currently at {{ $value }}"
